// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokMultiasset } from '../storyblok.d.ts';
export interface Alias {
  list?: "posts" | "projects";
  story?: ISbStoryData<Project> | ISbStoryData<Post> | string;
  width?: "1/3" | "1/2" | "2/3" | "1/1";
  new?: unknown;
  title?: string;
  description?: string;
  asset?: StoryblokMultiasset;
  href?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "alias";
  _uid: string;
  [k: string]: unknown;
}

export interface Carousel {
  id?: string;
  body: Cover[];
  fullHeight?: boolean;
  component: "carousel";
  _uid: string;
  [k: string]: unknown;
}

export interface Checkbox {
  id: string;
  label?: string;
  default?: boolean;
  required?: boolean;
  hidden?: boolean;
  component: "checkbox";
  _uid: string;
  [k: string]: unknown;
}

export interface Column {
  styles?: unknown;
  body?: (Text | Link | Image | Group)[];
  width?: "1/3" | "1/2" | "2/3" | "1/1";
  mode?: "card" | "accordion" | "menu";
  component: "column";
  _uid: string;
  [k: string]: unknown;
}

export interface Columns {
  styles?: unknown;
  id?: string;
  body: (Text | Image | Gallery | Alias | Column | Map)[];
  theme?: "primary" | "primary-dark" | "secondary" | "secondary-dark" | "dark";
  margin?: "slim" | "default" | "thick" | "screen";
  height?: boolean;
  align?: "top" | "center" | "bottom" | "fill";
  component: "columns";
  _uid: string;
  [k: string]: unknown;
}

export interface Cover {
  styles?: unknown;
  id?: string;
  body: (Text | Image | Link | Form | Group)[];
  image?: StoryblokAsset;
  theme?: "primary" | "primary-dark" | "secondary" | "secondary-dark" | "dark";
  blurred?: boolean;
  margin?: "slim" | "default" | "thick" | "screen";
  height?: boolean;
  justify?: "left" | "center" | "right";
  align?: "top" | "center" | "bottom";
  component: "cover";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  image?: StoryblokAsset;
  body?: Text[];
  copyright: string;
  terms: string;
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface Form {
  event: "" | "contact" | "download";
  lists?: ""[];
  messages?: unknown;
  headline?: string;
  success?: string;
  error?: string;
  fields?: (Checkbox | Input | Picker | Select | Slider)[];
  settings?: unknown;
  display?: "modal" | "drawer";
  label?: string;
  identify?: boolean;
  component: "form";
  _uid: string;
  [k: string]: unknown;
}

export interface Gallery {
  styles?: unknown;
  width?: "1/3" | "1/2" | "2/3" | "1/1";
  assets: StoryblokMultiasset;
  size?: "" | "brand" | "image";
  overlay?: boolean;
  component: "gallery";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  id?: string;
  list: "posts" | "projects";
  heading?: string;
  filters?: boolean;
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Group {
  body?: (Image | Link)[];
  component: "group";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  image?: StoryblokAsset;
  links?: Link[];
  fixed?: boolean;
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface Image {
  asset?: StoryblokAsset;
  picker?: unknown;
  color?: string;
  caption?: string;
  styles?: unknown;
  width?: "1/3" | "1/2" | "2/3" | "1/1";
  size?: "small" | "medium" | "large";
  crop?: boolean;
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface Input {
  id: string;
  label?: string;
  placeholder?: string;
  type: "email" | "text" | "tel" | "file";
  required?: boolean;
  hidden?: boolean;
  area?: boolean;
  component: "input";
  _uid: string;
  [k: string]: unknown;
}

export interface Link {
  label: string;
  href: StoryblokMultilink;
  button?: boolean;
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface Location {
  title?: string;
  address?: string;
  gps?: string;
  direction?: string;
  component: "location";
  _uid: string;
  [k: string]: unknown;
}

export interface Map {
  styles?: unknown;
  width?: "1/3" | "1/2" | "2/3" | "screen";
  dark?: boolean;
  id?: string;
  locations: (ISbStoryData<Location> | string)[];
  component: "map";
  _uid: string;
  [k: string]: unknown;
}

export interface Option {
  name: string;
  value: string;
  component: "option";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  meta?: unknown;
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  body?: (Cover | Carousel | Columns | Form | Grid)[];
  header?: ISbStoryData<Header> | string;
  footer?: ISbStoryData<Footer> | string;
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Picker {
  id: string;
  label?: string;
  default?: string;
  required?: boolean;
  hidden?: boolean;
  component: "picker";
  _uid: string;
  [k: string]: unknown;
}

export interface Post {
  title: string;
  description: string;
  image: StoryblokAsset;
  author?: string;
  body?: (Columns | Form)[];
  header?: ISbStoryData<Header> | string;
  footer?: ISbStoryData<Footer> | string;
  component: "post";
  _uid: string;
  [k: string]: unknown;
}

export interface Project {
  title: string;
  description: string;
  image: StoryblokAsset;
  contexts?: string;
  author?: string;
  type?: "" | "Tipologia 1" | "Tipologia 2" | "Tipologia 3" | "Tipologia 4";
  body?: (Cover | Carousel | Form | Columns)[];
  header?: ISbStoryData<Header> | string;
  footer?: ISbStoryData<Footer> | string;
  component: "project";
  _uid: string;
  [k: string]: unknown;
}

export interface Select {
  id: string;
  label?: string;
  placeholder?: string;
  options: Option[];
  multiple?: boolean;
  required?: boolean;
  hidden?: boolean;
  component: "select";
  _uid: string;
  [k: string]: unknown;
}

export interface Slider {
  id: string;
  label?: string;
  default: string;
  step?: string;
  min: string;
  max: string;
  unit?: "distance" | "surface" | "currency";
  required?: boolean;
  hidden?: boolean;
  component: "slider";
  _uid: string;
  [k: string]: unknown;
}

export interface Steps {
  id?: string;
  styles?: unknown;
  theme?: "primary" | "primary-dark" | "secondary" | "secondary-dark" | "dark";
  timeline?: boolean;
  heading?: string;
  body?: Column[];
  component: "steps";
  _uid: string;
  [k: string]: unknown;
}

export interface Text {
  styles?: unknown;
  headline?: string;
  content?: string;
  width?: "1/4" | "1/3" | "1/2" | "2/3" | "1/1";
  justify?: "spaced" | "center" | "right";
  level?: "high" | "low";
  component: "text";
  _uid: string;
  [k: string]: unknown;
}
