// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokMultiasset, StoryblokAsset, StoryblokMultilink } from '../storyblok.d.ts';
export interface Album {
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  tracks?: string;
  component: "album";
  _uid: string;
  [k: string]: unknown;
}

export interface Alias {
  heading?: string;
  story?: "article" | "news" | "album";
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  theme?: "" | "primary" | "secondary" | "primary-dark" | "secondary-dark" | "dark";
  component: "alias";
  _uid: string;
  [k: string]: unknown;
}

export interface Column {
  body?: (Column | Gallery | Image | Link | Text | Video)[];
  component: "column";
  _uid: string;
  [k: string]: unknown;
}

export interface Cover {
  body?: (Column | Gallery | Image | Link | Text | Video)[];
  source?: StoryblokAsset;
  height?: "full" | "huge" | "large";
  align?: "top" | "bottom";
  theme?: "primary" | "secondary" | "primary-dark" | "secondary-dark" | "dark";
  component: "cover";
  _uid: string;
  [k: string]: unknown;
}

export interface Event {
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  date?: string;
  location?: string;
  ticket?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "event";
  _uid: string;
  [k: string]: unknown;
}

export interface Footer {
  logo?: StoryblokAsset;
  body?: Text[];
  copyright?: string;
  component: "footer";
  _uid: string;
  [k: string]: unknown;
}

export interface Gallery {
  sources?: StoryblokMultiasset;
  component: "gallery";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  heading?: string;
  story?: "" | "events" | "news";
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Header {
  logo?: StoryblokAsset;
  menu?: Link[];
  component: "header";
  _uid: string;
  [k: string]: unknown;
}

export interface Image {
  source?: StoryblokAsset;
  size?: "" | "small" | "medium" | "large" | "fill";
  component: "image";
  _uid: string;
  [k: string]: unknown;
}

export interface Link {
  label?: string;
  href?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  asButton?: boolean;
  theme?: "primary" | "secondary" | "primary-dark" | "secondary-dark" | "dark";
  component: "link";
  _uid: string;
  [k: string]: unknown;
}

export interface News {
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  body?: (Alias | Cover | Footer | Grid | Header | Section)[];
  component: "news";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  meta?: unknown;
  header?: ISbStoryData<Header> | string;
  footer?: ISbStoryData<Footer> | string;
  body?: (Alias | Cover | Footer | Grid | Header | Section)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Section {
  heading?: string;
  body?: (Column | Gallery | Image | Link | Text | Video)[];
  justify?: "center" | "right" | "spaced";
  theme?: "primary" | "secondary" | "primary-dark" | "secondary-dark" | "dark";
  component: "section";
  _uid: string;
  [k: string]: unknown;
}

export interface Text {
  content?: string;
  component: "text";
  _uid: string;
  [k: string]: unknown;
}

export interface Video {
  youtube?: string;
  component: "video";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Album | Event | Footer | Header | News | Page;
